### PR TITLE
Add developer guide to pkgdown site

### LINKED ISSUE #735: dev guide
- [x] create new article page for the dev guide, and links to the following pages
- [x] #637 
- [x] #614

### PR DESCRIPTION
**Pull request by edelarua**
Closes #735 

Individual `.Rmd` files can be merged in first from their branches.

`.html` files need to be manually formatted & generated formatted via the "Knit" button since they are not stored in the Articles section.

To merge:

- [x] #614 
- [ ] #637

### CODE REVIEW

**Comment by Melkiades** [comment]
@edelarua I am wondering if you want to merge our branches here or first main and then this

**Comment by edelarua** [comment]
> @edelarua I am wondering if you want to merge our branches here or first main and then this

Either one works - I was just working on getting the output in the site how we will want it.

**Comment by shajoezhu** [comment]
hey guys, thanks for the changes here. Let's unblock this after the current release

**Review by Melkiades — APPROVED** [review]
Looks very good to me! Lets see what is the output for navbar... no icon? :D Thanks Emily for working this out

**Pull request merged**
