### PR TITLE
split package

### PR DESCRIPTION
**Pull request by shajoezhu**

### CODE REVIEW

**Review by Melkiades — APPROVED** [review]
Lgtm! Thanks Joe. Was wondering if we should change the name of tt_to_flextable ... wdyt?

**Comment by shajoezhu** [comment]
> Lgtm! Thanks Joe. Was wondering if we should change the name of tt_to_flextable ... wdyt?

sure. lets discuss tomorrow in meetings :) thanks man

**Comment by vedhav** [comment]
Hello team,
The `rtables::tt_to_flextable` [was being used in teal.reporter](https://github.com/insightsengineering/teal.reporter/blob/4fefa7ebac08caac2ca7b6588e497613ac4676fc/R/utils.R#L128-L146). Is Am I right to assume that we should start using this function from the [rtables.officer package](https://github.com/insightsengineering/rtables.officer/blob/bd9545dacf03f59409ef3eb20215d3dcb3ba4bf4/R/tt_as_flextable.R#L100)? If so, here's the [PR in teal.reporter](https://github.com/insightsengineering/teal.reporter/pull/289).
Can we please add this change in the `NEWS.md` so it can help old users migrate?

**Comment by vedhav** [comment]
There was no new change made to `teal.reporter` so we do not plan to release it anytime soon. cc @shajoezhu

**Comment by averissimo** [comment]
Once the release of the `rtables.officer` approaches, consider contacting `blockr` developers and others about the change as it might break other packages.

`tt_to_flextable` alone seems to be used in other places 😅

- [BristolMyersSquibb/blockr.export](https://github.com/BristolMyersSquibb/blockr.export/blob/6bbcae877b60dbb495a89aa32b5e33f10057dcca/R/code.R#L64)
- [ahasoplakus/pharmtables](https://github.com/ahasoplakus/pharmtables/blob/101e6681f4f09c2912808c26858d788793d0ee05/NAMESPACE#L100)
- [RConsortium/rtrs-wg](https://github.com/RConsortium/rtrs-wg/blob/da4b14e530b89758bba66c338bf5226f3c0b0e4d/tables-book/04-04-concomitant-medications.Rmd#L71)
and [other minor ones](https://github.com/search?q=tt_to_flextable&type=code)

**Comment by shajoezhu** [comment]
thanks alot @averissimo

**Pull request merged**
