### PR TITLE
261 truetype pag new

### PR DESCRIPTION
**Pull request by gmbecker**
Goes with insightsengineering/formatters#261

Implements column expression logic to support fully custom split functions in column space and truetype font support

### CODE REVIEW

**Comment by gmbecker** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gmbecker** [comment]
recheck

**Comment by Melkiades** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Melkiades** [comment]
recheck

**Comment by shajoezhu** [comment]
we can close this now

**Pull request closed without merging**
