### PR TITLE
Design cheatsheet

### LINKED ISSUE #600: Creation of a cheatsheet for rtables
I think this would be amazingly useful as often I get lost looking for a specific function that I know exists but I do not remember exactly which it is. 

credit: @BFalquet

### PR DESCRIPTION
**Pull request by edelarua**
Closes #600

### CODE REVIEW

**Comment by shajoezhu** [comment]
update the bottom right contact info, 

image

with github rtables issue board link

**Comment by shajoezhu** [comment]
I think this is rather advanced usage with very little explaination, consider for removal

image

**Comment by shajoezhu** [comment]
This link is very good. 

suggest to add links to all panels, and link to vignette

image

**Review by shajoezhu — CHANGES_REQUESTED** [review]
Hi @edelarua , it looks very good for the first draft, I made a few suggestions. Thanks!

**Comment by khatril** [comment]
Hey @edelarua it looks great, a nice first draft! I have some suggestions too
1. Have an introductory sentence near the header, e.g. "rtables - reporting tables with R. The rtables R package is designed to create and display complex tables with R" could also have this in the Basics section and combine with the title. Similar to the tidyr cheatsheet.

2. Add some context behind the 'Basics' section, e.g. basic_table, every table layout must start with basic_table. And similar for build_table. 

3. I found the Accessors & Modify layout could be a bit more readable, could consider adding the example image underneath the code (happy to elaborate on this point if it doesn't make sense), 

3. Sorting & Pruning, minor comment but could you highlight the sort_at_path function in yellow in the example code so it draws attention to this function.

Happy to touch base to discuss the points with others once all other reviews are done

**Review by shajoezhu — APPROVED** [review]
It's beautiful! Thanks a lot Em!

**Pull request merged**
