### PR TITLE
catch bad labels (with {}) and throw informative error

### PR DESCRIPTION
**Pull request by gmbecker**

### CODE REVIEW

**Comment by gmbecker** [comment]
@cicdguy this is failing the roxygen check in the job (though not locally), specifically regarding the `export_as_pdf` function. The issue is that there are no changes to `export_as_pdf` or its roxygen comment in this PR.

Any idea whats happening here (and similarly in other PRs, it seems)?

**Comment by gmbecker** [comment]
> @cicdguy this is failing the roxygen check in the job (though not locally), specifically regarding the `export_as_pdf` function. The issue is that there are no changes to `export_as_pdf` or its roxygen comment in this PR.
> 
> Any idea whats happening here (and similarly in other PRs, it seems)?

So the issue is staged dependencies grabbing updated versions of formatters, and our use of `@inheritParams formatters::export_as_txt` in the documentation to `export_as_pdf`.

Not entirely sure what to do about this, but its an issue the automation team should be aware of, and it'd be great to get some mitigation/flagging if possible.

**Comment by shajoezhu** [comment]
> @cicdguy this is failing the roxygen check in the job (though not locally), specifically regarding the export_as_pdf function. The issue is that there are no changes to export_as_pdf or its roxygen comment in this PR.

Roxygen issue should be fixed now

**Review by shajoezhu — APPROVED** [review]
thanks a lot Gabe! the message is more informatvie

**Comment by shajoezhu** [comment]
close #671

**Pull request merged**
